import os
import requests
import json
from dotenv import load_dotenv

load_dotenv()
OPENROUTER_KEY = os.getenv("OPENROUTER_API_KEY")

def ask_model(question: str) -> str:
    if not OPENROUTER_KEY:
        raise Exception("OpenRouter API key is not set in environment variables")

    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {OPENROUTER_KEY}",
        "Content-Type": "application/json"
    }

    prompt = f"""
Convert this user request to a SQL SELECT query for a database table `students`.
Only return the SQL query.
User request: "{question}"
Ensure the query starts with SELECT.
    """

    response = requests.post(
        url,
        headers=headers,
        data=json.dumps({
            "model": "gpt-4o-mini",
            "messages": [{"role": "user", "content": prompt}]
        }),
        timeout=10
    )

    response.raise_for_status()
    data = response.json()
    sql = data["choices"][0]["message"]["content"].strip()

    # Проверяем, что SQL начинается с SELECT
    if not sql.lower().startswith("select"):
        raise Exception(f"Unsafe SQL generated by model: {sql}")

    return sql
